spring.profiles.active=dev
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# JPA/Hibernate 설정

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Naver API settings (임시 더미 값)
social.client.naver.rest-api-key=dummy-naver-api-key
social.client.naver.secret-key=dummy-naver-secret-key
social.client.naver.redirect-uri=http://localhost:8080/naver/callback
social.client.naver.grant_type=authorization_code
